name = "Performance Modpack"
author = "Vincent Schweiger"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb7aad082a8db135d52f9ff42ad501f2da8ba2ae65c47ec889fced194ba0ee7e"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
